### ISSUE TITLE
Allow not to create the cache_folder

### ISSUE THREAD

**Issue by lebouquetin** [algoo/preview-generator#1]
Current status:
PreviewManager has a parameter "cache_path". If the given path does not exist, then PreviewManager creates it silently.

Expected:
Add a create_folder boolean parameter, default value to False.
If create_folder is True, then creates the folder if it does not exist.
Else, raise an exception.

See the following thread for which exception to raise: http://stackoverflow.com/questions/8978057/raising-builtin-exception-with-default-message-in-python

**Comment by herawo** [comment]
Done with the units tests that goes along.
