### ISSUE TITLE
Unsupported mimetype: application/vnd.openxmlformats-officedocument.wordprocessingml.document

### ISSUE THREAD

**Issue by AtulCIS** [algoo/preview-generator#156]
I am using preview-generator to make a pdf from docx file in Django. The code is working properly in my local machine but the same deployment is not working on the server which is ubuntu 18.04. I am having Unsupported mimetype: application/vnd.openxmlformats-officedocument.wordprocessingml.document error. I have researched about it and found libre office needs to be installed in the server and its already present on my server. can you please suggest what I need to do or how I can define path of libre office. 

I am using Django and once I use the shell the file generated properly but in the the web its not working.
This is the error on terminal.

```
gunicorn[29453]: Builder <class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'> is missing a dependency: this builder requires inkscape to be available
gunicorn[29453]: Builder <class 'preview_generator.preview.builder.image__imconvert.ImagePreviewBuilderIMConvert'> is missing a dependency: this builder requires convert to be available
Builder <class 'preview_generator.preview.builder.document_generic.DocumentPreviewBuilder'> is missing a dependency: this builder requires qpdf to be available
Builder <class 'preview_generator.preview.builder.document__scribus.DocumentPreviewBuilderScribus'> is missing a dependency: this builder Builder <class 'preview_generator.preview.builder.office__libreoffice.OfficePreviewBuilderLibreoffice'> is missing a dependency: this builder requires libreoffice to be available
```

**Comment by inkhey** [comment]
Look like "libreoffice" executable isn't available for python code.
Can you use same python environnement as your code and test this in a python console:

`
from preview_generator.preview.builder.office__libreoffice import OfficePreviewBuilderLibreoffice
builder = OfficePreviewBuilderLibreoffice()
builder.check_dependencies()
`

You can also try : 
`
which libreoffice 
`
In my own system, i get this result:
`
/usr/bin/libreoffice
`

If these command failed, a simple hack to fix this will be to add a symlink from /usr/bin/libreoffice to real libreoffice binary.

**Comment by inkhey** [comment]
note: having executable/valid symlink in /usr/bin/libreoffice, should work in simple case. Thing can be handled differently: 
- User that run python script (www-data ?) should have right to run libreoffice binary (check `ls -l /usr/bin/libreoffice`)
- You can use a customized user PATH (so /usr/bin may be not accessible), in this case you should have libreoffice binary in one of the path you provided in PATH variable.

**Comment by AtulCIS** [comment]
@inkhey  I have executable "libreoffice". When I run code on server with python manage.py runserver its generating the PDF file properly, but if I use gunicorn to serve the site then I am having the issue mentioned.  My libre office path is "/usr/bin/libreoffice". Can I give a path variable in settings file if yes then what can be the variable name.

**Comment by inkhey** [comment]
> @inkhey I have executable "libreoffice". When I run code on server with python manage.py runserver its generating the PDF file properly, but if I use gunicorn to serve the site then I am having the issue mentioned. My libre office path is "/usr/bin/libreoffice". Can I give a path variable in settings file if yes then what can be the variable name.

Did you run python manage.py with the same user as the one used by gunicorn to run server code ?
It's look like gunicorn context doesn't allow access to `/usr/bin/libreoffice`.

**Comment by AtulCIS** [comment]
[Unit]
Description=Gunicorn instance to serve myproject
After=network.target

[Service]
User=root
Group=root
WorkingDirectory=/root/form_builder
Environment="PATH=/root/form_builder/.county_form/bin"
ExecStart=/root/form_builder/.county_form/bin/gunicorn --workers 10 --bind unix:county_form.sock  --access-logfile /root/form_builder/logs/gunicorn-access.log --error-logfile /root/form_builder/logs/gunicorn-error.log --log-level warn  --timeout 3600 -b  0.0.0.0:8001 --limit-request-line 0 --limit-request-field_size 0 county_form.wsgi:application

[Install]
WantedBy=multi-user.target

Yes, Root user.

**Comment by inkhey** [comment]
> [Unit]
> Description=Gunicorn instance to serve myproject
> After=network.target
> 
> [Service]
> User=root
> Group=root
> WorkingDirectory=/root/form_builder
> Environment="PATH=/root/form_builder/.county_form/bin"
> ExecStart=/root/form_builder/.county_form/bin/gunicorn --workers 10 --bind unix:county_form.sock --access-logfile /root/form_builder/logs/gunicorn-access.log --error-logfile /root/form_builder/logs/gunicorn-error.log --log-level warn --timeout 3600 -b 0.0.0.0:8001 --limit-request-line 0 --limit-request-field_size 0 county_form.wsgi:application
> 
> [Install]
> WantedBy=multi-user.target
> 
> Yes, Root user.

It's look like PATH is overriden by `/root/form_builder/.county_form/bin`, try add "libreoffice" symlink in this folder. If this is the issue, you will probably need to add other symlink depending on which builder you need. You may need convert(most image types), inkscape(svg), qpdf(pdf) and potentially scribus(scribus file).

**Comment by AtulCIS** [comment]
@inkhey Thanks. I have added symlink for all the dependencies. The error log does not have any error now but the file is not generating till now. I am having 503 error on it.

**Comment by AtulCIS** [comment]
This is the error log now 
Command '['libreoffice', '--headless', '--convert-to', 'pdf:writer_pdf_Export', '/root/form_builder/static/temp_folder/ae930030d03d31ca938f971a839238b5.pdf.docx', '--outdir', '/root/form_builder/static/temp_folder/', '-env:UserInstallation=file:///tmp/LibreOffice_Conversion_${USER}']' returned non-zero exit status 127

**Comment by inkhey** [comment]
@AtulCIS 
can you try run as same user as script (root in your case) the command : 

> libreoffice --headless --convert-to pdf:writer_pdf_Export  /root/form_builder/static/temp_folder/ae930030d03d31ca938f971a839238b5.pdf.docx /root/form_builder/static/temp_folder/ -env:UserInstallation=file:///tmp/LibreOffice_Conversion_${USER}

and then : 
> echo $?

You will probably get some error after first command which can help us to know where the issue come from. second command is just to verify we get same exit status as script (we should get 127).

**Comment by AtulCIS** [comment]
This is the error 
convert /root/form_builder/static/temp_folder/ae930030d03d31ca938f971a839238b5.docx -> /root/ae930030d03d31ca938f971a839238b5.pdf using filter : writer_pdf_Export
Error: source file could not be loaded

**Comment by inkhey** [comment]
> This is the error
> convert /root/form_builder/static/temp_folder/ae930030d03d31ca938f971a839238b5.docx -> /root/ae930030d03d31ca938f971a839238b5.pdf using filter : writer_pdf_Export
> Error: source file could not be loaded

can you check if  /root/form_builder/static/temp_folder dir exist ?

**Comment by AtulCIS** [comment]
yes it exists.

**Comment by AtulCIS** [comment]
FINALLY! I have fixed the issue by removing Environment="PATH=/root/form_builder/.county_form/bin" from my gunicorn server.
