### ISSUE TITLE
Adding dependencies for fedora users/dev

### ISSUE THREAD

**Issue by PhilippeGalvan** [algoo/preview-generator#181]
Hi !

As a fedora user it looks like I have very different dependency names and I don't find all equivalents.

For example I'm struggling to find the fedora package for `python3-pythonmagick`. 

Is it possible to add in the constribute.rst a part for fedora users including fedora related dependencies?

**Comment by inkhey** [comment]
Hello,  `python3-pythonmagick `is not required anymore. 

We don't expect to support fedora for now, please free to add documentation about installation on fedora

ticket related to other platform support #241
