### ISSUE TITLE
Gettig Error "Skipping builder class"

### ISSUE THREAD

**Issue by pradeekumar** [algoo/preview-generator#19]
Skipping builder class [<class 'preview_generator.preview.generic_preview.OnePagePreviewBuilder'>]: method **get_supported_mimetypes is not implemented**
Skipping builder class [<class 'preview_generator.preview.generic_preview.ImagePreviewBuilder'>]: method **get_supported_mimetypes is not implemented**
Error while checking dependencies:  [Errno 2] No such file or directory: 'inkscape': 'inkscape'

**Comment by buxx** [comment]
Hello,

Can you provide a code example to reproduce ? And some information about your OS/python version etc.

Thank's.

**Comment by pradeekumar** [comment]
Hi @buxx,
I solved my problem by changing the **print** statement to **logging.debug**
It was an exception that was getting print.

**Comment by buxx** [comment]
Okay,
Good continuation !
bux.
