### ISSUE TITLE
Feat: Use modern an maintained library for pdf generation instead of pypdf2

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#192]
We currently get many trouble with pypdf2:
- https://github.com/algoo/preview-generator/issues/80
- https://github.com/algoo/preview-generator/issues/54
- https://github.com/algoo/preview-generator/issues/23
- https://github.com/algoo/preview-generator/issues/23#issuecomment-659836263

This library is not properly maintained (now a new project pypdf4 exist)
We should find a pdf library that can handle properly those use case and recreate a new pdf builder.
Poppler seems the way to go : https://en.wikipedia.org/wiki/Poppler_(software) (used by libreoffice, evince, inkscape, etc...)

**Comment by inkhey** [comment]
Note: I see two alternative project for a modern and correctly maintenained pdf builder:
- https://pypi.org/project/python-poppler/ python binding for poppler, need python 3.7 or more.
- https://pypi.org/project/pikepdf/ based on qpdf, usable with python 3.5, qpdf is already what we used for decryption.

**Comment by titusz** [comment]
have a look at: https://github.com/pymupdf/PyMuPDF

**Comment by inkhey** [comment]
Another solution may be simply use poppler-utils : https://packages.debian.org/fr/bullseye/poppler-utils instead of python-poppler lib, this avoid license issues (poppler is gpl) and having weak connection has some benefit (seems easier to make timeout for example).

**Comment by inkhey** [comment]
fixed by the poppler based builder #275
