### ISSUE TITLE
Regression: PDF preview page of an ODT file is blank

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#194]
Due to the fix described in https://github.com/algoo/preview-generator/pull/100#discussion_r303020089, specific PDF page previews of office documents are empty.

> 
> regression found here: 
> for unknown reason, using stream instead of file path in get_decrypted_pdf() which use PdfFileReader inside doesn't provide a correct pdf (it result in an empty pdf).
> see https://github.com/algoo/preview-generator/issues/194
> 
> _Originally posted by @inkhey in https://github.com/algoo/preview-generator/pull/100#discussion_r463565867_

Related Tracim issue : https://github.com/tracim/tracim/issues/3401

# Implemented solution:
https://github.com/algoo/preview-generator/pull/200
Hack to convert stream in a known working format for pypdf2, this is not an effective solution (as this lead to in memory content), but this does work and is not a regression (we do use the same "code" as pypdf2 itself use for file).

**Comment by PhilippeAccorsi** [comment]
This regression is visible/exists in Tracim (latest release) ?

**Comment by inkhey** [comment]
> This regression is visible/exists in Tracim (latest release) ?

The fix was added in preview generator 0.15.4 that tracim is using.

**Comment by PhilippeAccorsi** [comment]
So this issue need to be stay open or can be closed ?

**Comment by inkhey** [comment]
We can close it.
