### ISSUE TITLE
Cache file naming rules

### ISSUE THREAD

**Issue by lebouquetin** [algoo/preview-generator#2]
**page number in the file name**

Currently :
the id of the page appears in the filename as _(pageid)_. this is source of problems when working in a terminal (parenthesis must be escaped).

Expected: Replace _(pageid)_ by _--page-pageid_

**original filename appears in cache file name**

Currently:
when building preview of a file myfile.jpeg, the myfile part appears in the cache filename. This is not required and may be problematic when file names includes special chars
BUT this may help investigating some issues or some cache.

Expected
add a _use_original_filename_ boolean parameter in the PreviewManager constructor. Then, when building cache file, includes the original filename only if the use_original_filename is True. In the other case, only use the md5sum.

**Comment by herawo** [comment]
Done with units tests thats goes along.
