### ISSUE TITLE
pyexifinfo - Preventing installation of Preview-Generator

### ISSUE THREAD

**Issue by ironfelix717** [algoo/preview-generator#213]
HI,

It appears pyexifinfo is halting my installation. What a crap shoot. How do I solve this?

_pip install preview-generator:_
`Collecting pyexifinfo
  Using cached pyexifinfo-0.4.0.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\USERNAME\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-x_slvbfm\\pyexifinfo\\setup.py'"'"'; __file__='"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-x_slvbfm\\pyexifinfo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info'
         cwd: C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\
    Complete output (21 lines):
    running egg_info
    creating C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info\pyexifinfo.egg-info
    writing C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info\pyexifinfo.egg-info\PKG-INFO
    writing dependency_links to C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info\pyexifinfo.egg-info\dependency_links.txt
    writing top-level names to C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info\pyexifinfo.egg-info\top_level.txt
    writing manifest file 'C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info\pyexifinfo.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info\pyexifinfo.egg-info\SOURCES.txt'
    writing manifest file 'C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\pip-egg-info\pyexifinfo.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\setup.py", line 95, in <module>
        result = check_if_exiftool_is_already_installed()
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-x_slvbfm\pyexifinfo\setup.py", line 51, in check_if_exiftool_is_already_installed
        stderr = fnull
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\subprocess.py", line 339, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\USERNAME\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.`

**Comment by inkhey** [comment]
Hello !
It's seems that exiftool is missing in your case, but it's probably not the only issue you will face, as you are running on a untested operating system.

Preview_generator rely on multiple non-python librairie to run like exiftool but also poppler, imagemagick, etc... 
We do use preview_generator on debian, so we don't know how to run it on windows, but if you are motivated, you can try translate the build dependency for debian/ubuntu into windows one:
```
apt-get install zlib1g-dev libjpeg-dev python3-pythonmagick inkscape xvfb poppler-utils libfile-mimeinfo-perl qpdf libimage-exiftool-perl ufraw-batch ffmpeg
```
(from https://github.com/algoo/preview-generator#installation)
I suggest you first installing exiftool and see how far you get with it.

An alternative solution depending on what you need may be simply running the code in debian.

**Comment by ironfelix717** [comment]
Hi, thanks for your reply. I tried installing PyExifTool by itself and it failed also. The README or the github page does not specify that this is not supported on Windows.

**Comment by inkhey** [comment]
related to windows support #241
