### ISSUE TITLE
Feat: Better Raw preview builder with Darktable-cli or rawpy ?

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#249]
## Feature description and goals

Darktable as a command line permitting to generate jpg image from raw with specific treatment on it.
With a good default preset, we may be able to generate good raw preview with it.

External links:
- https://www.darktable.org/usermanual/en/special-topics/program-invocation/darktable-cli/

**Comment by grignards** [comment]
I also found https://github.com/letmaik/rawpy which could be used and avoids to install a full application just to convert files types.

**Comment by grignards** [comment]
`rawpy` is only a wrapper on top of `libraw`, the supported cameras are listed on [libraw website](https://www.libraw.org/supported-cameras).

**Comment by inkhey** [comment]
@grignards Just found this:
https://www.libraw.org/

> Additionally, the LibRaw library offers some basic RAW conversion, intended for cases when such conversion is not the main function of the LibRaw-using application (for example: **a viewer for 500+ graphic file formats, including RAW**). These methods are inherited from the Dave Coffin’s dcraw.c utility (see below the “Project history” section)**; their further development is not currently planned, because we do not consider production-quality rendering to be in the scope of LibRaw’s functionality** (the methods are retained for compatibility with prior versions and for rapid-fire testing of RAW support and other aspects).

**Comment by inkhey** [comment]
fixed by #278
