### ISSUE TITLE
Implement support of gimp files preview

### ISSUE THREAD

**Issue by lebouquetin** [algoo/preview-generator#26]
Preview-generator does not support gimp file preview (`.xcf`). Expected : offer a preview of gimp files.

A direction to look at is to use `xcf2png`: `xcf2png -C ./pycon/tshirt/dos.xcf | convert - -resize <width>x<height> /tmp/dos.jpeg`

Another solution would be to use `gegl`

**Comment by inkhey** [comment]
another solution maybe to use directly imagemagick xcf support like in wikimedia commons, for example : https://commons.wikimedia.org/wiki/File:Gps-multipath-efect.xcf

**Comment by lebouquetin** [comment]
@inkhey you right. I did investigate yesterday evening and I have a prototype based on `convert`. It should support same mimetypes as wand and works very well with gimp files I tested with.

We'll probably use this solution (need to be better integrated and tested in preview-generator)
