### ISSUE TITLE
Bug: Weird result on png file.

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#261]
## Description and expectations

Some png file return wrong background color for preview as jpeg + the quality obtain is poor.

### How to reproduce

- download this image as `tree.png`: ![tree.png](https://user-images.githubusercontent.com/7851652/124591671-db262600-de5c-11eb-9872-94603abe1bfc.png)
 - launch `preview tree.png`
 - get this image: ![291a73ceb919c34feacd58ee1f1ae9f4-256x256](https://user-images.githubusercontent.com/7851652/124591917-29d3c000-de5d-11eb-834f-c3e2fe6c4414.jpeg)

### Version information

- Version: 0.23
- Device / System: Ubuntu 18.04

## Diagnostic

The problem is that:
- both preview-generator imagemagick and pillow builder support png (note : imagemagick use pillow for resizing)
- the imagemagick builder has a bigger priority, so it is used for png.
- only the pillow does support correctly the png to jpeg convertion for now (add background, quality result).

Note: the background color used by imagemagick for jpeg to png convertion differ between file. for this other file, the background is ok, so the bug does not concern all png files:
- 
![Arbre](https://user-images.githubusercontent.com/7851652/124592776-1e34c900-de5e-11eb-8512-fa87f547e4ea.png)
generate:
![2508fe7533f7ea2581118ca064e2e3db-256x256](https://user-images.githubusercontent.com/7851652/124592814-28ef5e00-de5e-11eb-9c35-5fae3c23c0d9.jpeg)

**Comment by inkhey** [comment]
I create a fix for this: https://github.com/algoo/preview-generator/pull/262 . This fix:
- prefer pillow than imagemagick.
- do not use imagemagick for png.
- keep alpha canal when converting with imagemagick to png.


During test, i  also discover that as we do use intermediate png, it may create huge png file from compressed format like jpeg (for exemple a 7Mo jpeg can create a 40mo png). 

I do suggest to solve this by removing the intermediate format for img builder. This also mean we should take care of having similar quality result between pillow and img builder, similar background color, etc...

**Comment by tonypottera24** [comment]
I agree with @inkhey, especially running this in memory limited dockers.

**Comment by inkhey** [comment]
This issue as been solved with the wand backend
