### ISSUE TITLE
Preview of video files

### ISSUE THREAD

**Issue by lebouquetin** [algoo/preview-generator#27]
Currently, preview-generator does not allow preview of video files.

Expected: generate an image preview of video files.

Here is a way to do so:

1. get video file duration in seconds: `ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 <videofile>`
2. compute the timeframe at 5% (ie duration/20)
3. extract the frame : `ffmpeg -ss <timeframe> -i <videofile> -vframes 1 -q:v 2 <preview.jpeg>

Finally, the right way to implement video preview generation would better be based on https://github.com/kkroening/ffmpeg-python

**Comment by lebouquetin** [comment]
Note : implementing support of video files in preview generator should come with mediainfo features for extracting video metadata (for json preview)

**Comment by lebouquetin** [comment]
@aKtasos you take this feature?

**Comment by inkhey** [comment]
fixed by https://github.com/algoo/preview-generator/pull/138

**Comment by Alynva** [comment]
How to use it? It says that "video/mp4" is not supported.

**Comment by raphj** [comment]
@Alynva Can you give us more information on what you are trying to achieve? What is your setup? How are you using preview-generator? Can you provide us with a snippet of code exhibiting your issue?

**Comment by otavs** [comment]
Hi @raphj, I opened issue https://github.com/algoo/preview-generator/issues/232 with details, I'm working with @Alynva :)
