### ISSUE TITLE
Why is it that when previewing an image, it is first converted to png and then cropped to jpg with pillow?

### ISSUE THREAD

**Issue by a523** [algoo/preview-generator#271]
I have tested， preview the image file (whether it is a jpg file or a png file ),  the also call `ImagePreviewBuilderIMConvert` to convert  to png and then  call `ImagePreviewBuilderPillow` ？
Why？ 
Why do not use  ImagePreviewBuilderPillow directly? 

I am use the latest code on the develop branch .

**Comment by a523** [comment]
I found a best practice on producing thumbnails with ImageMagick：
https://legacy.imagemagick.org/Usage/thumbnails/

**Comment by a523** [comment]
Hi，@inkhey  I have proposed a PR to fix this ,please review it.

**Comment by inkhey** [comment]
fixed by #274
