### ISSUE TITLE
Bug:  Strange aspect ratios appear when previewing photos taken with some special devices

### ISSUE THREAD

**Issue by a523** [algoo/preview-generator#293]
## Description and expectations
- On some pictures that taken by specific devices, like this :
![IMG_20220106_154340](https://user-images.githubusercontent.com/21216466/149743830-2919ae6b-4140-4b0c-8ecb-50872086ee94.jpg)
- preview got:
![34b53c318d41cecfd58f59bb3afefb73-256x256](https://user-images.githubusercontent.com/21216466/149746264-b247a1da-4a47-4d28-b3a6-ce1475e58db6.jpeg)

- cause:
The original image doesn't have the correct orientation, but most image viewing software will automatically correct it, our imagemagick will too, the problem is that when we calculate the target height and width, it is based on the original image before rotation.

- Fix
Calculate target size, should be based on rotated size

### How to reproduce
as above

### Version information

- Version: [0.28]
- Device / System: [e.g. Debian Buster]

## Prerequisites

 I'm going to fix it by a pr.

**Comment by a523** [comment]
Now the got ：
![396449e0163a3b6bcce0b6d24a04c6b0-512x256](https://user-images.githubusercontent.com/21216466/149887243-660f9291-7205-405c-8ccb-4d0fbadebc90.jpeg)

**Comment by inkhey** [comment]
fixed by #294
