### ISSUE TITLE
Please license your repository

### ISSUE THREAD

**Issue by andersfylling** [algoo/preview-generator#304]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by garrypolley** [comment]
It is: https://github.com/algoo/preview-generator#license

**Comment by andersfylling** [comment]
Oh! I see. Would you also be open to use the github format, so it shows up in github overview? https://github.com/algoo/preview-generator/community/license/new?template=MIT

**Comment by lebouquetin** [comment]
I did it. I let developers validate my PR (not sure it is valid with our development standards)

**Comment by lebouquetin** [comment]
see https://github.com/algoo/preview-generator/pull/305
