### ISSUE TITLE
Page number broken for text file "Can't convert NoneType"

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#39]
using manager.get_page_nb on simple text file broke with  `TypeError: Can't convert 'NoneType' object to str implicitly`

Traceback:

> tests/input/txt/test_txt.py:80 (test_page_number__no_extension)
> def test_page_number__no_extension():
>         manager = PreviewManager(cache_folder_path=CACHE_DIR, create_folder=True)
>         page_number = manager.get_page_nb(
>           file_path=os.path.join(CURRENT_DIR, 'the_text_no_extension'),
>         )
> 
> ../../preview-generator/tests/input/txt/test_txt.py:84: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ../../preview-generator/preview_generator/manager.py:81: in get_page_nb
>     self.cache_path
> ../../preview-generator/preview_generator/preview/builder/document_generic.py:174: in get_page_number
>     cache_path=cache_path
> ../../preview-generator/preview_generator/preview/builder/document_generic.py:143: in build_pdf_preview
>     mimetype=mimetype
> ../../preview-generator/preview_generator/preview/builder/office__libreoffice.py:49: in _convert_to_pdf
>     cache_path, output_filepath, mimetype
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> file_content = <_io.BufferedReader name='/home/user/Public/preview-generator/tests/input/txt/the_text_no_extension'>
> input_extension = None, cache_path = '/tmp/preview-generator-tests/cache/'
> output_filepath = '/tmp/preview-generator-tests/cache/c6250e1070bf48e6814d8442d71f7ca2.pdf'
> mimetype = ''
> 
>     def convert_office_document_to_pdf(
>         file_content: typing.IO[bytes],
>         input_extension: str,  # example: '.dxf'
>         cache_path: str,
>         output_filepath: str,
>         mimetype: str
>     ) -> BytesIO:
>         logging.debug('converting file bytes {} to pdf file {}'.format(file_content, output_filepath))  # nopep8
>         if not input_extension:
>             input_extension = mimetypes.guess_extension(mimetype)
> >       temporary_input_content_path = output_filepath + input_extension  # nopep8
> E       TypeError: Can't convert 'NoneType' object to str implicitly
> 
> ../../preview-generator/preview_generator/preview/builder/office__libreoffice.py:63: TypeError

**Comment by lebouquetin** [comment]
Already fixed.
