### ISSUE TITLE
Json preview is not clear

### ISSUE THREAD

**Issue by lebouquetin** [algoo/preview-generator#4]
Currently, json preview of a zip returns a structure with values as a list instead of a dict. It's not clear what each information is.

Currently json preview of a zip is something like this:
```  {
  "file": [
    [
      "qab/",
      0,
      "2015-12-18 12:48:08"
    ],
    [
      "qab/options.php",
      186,
      "2015-12-18 12:48:06"
    ],
  }
```

Expected:

```{
  "files": [
    {
      "path": "qab/",
      "size": 0,
      "created": "2015-12-18 12:48:08"
    },
    {
      "path": "qab/options.php",
      "size": 186,
      "created": "2015-12-18 12:48:06"
    },
```

**Comment by lebouquetin** [comment]
Note : do the same for html preview which is not ready-to-read (add labels and a line return between each information)

**Comment by herawo** [comment]
Done for Json and HTML
