### ISSUE TITLE
Installation step clarifications

### ISSUE THREAD

**Issue by buxx** [algoo/preview-generator#46]
It seems README installation steps are not clear enough. It would be nice if README can be explicit on:

* What must be installed to make all preview working
* What must be installed to "specific" previews

**Comment by buxx** [comment]
Note: README is exhaustive in https://github.com/algoo/preview-generator#installation-dev- part but not in Install part.

**Comment by inkhey** [comment]
The documentation has been improved a lot since this issue was created, i close it. Be free to open a new ticket if something specific missing in the documentation.
