### ISSUE TITLE
add has_*_preview for all type of preview

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#48]
Currently only "pdf" has a "has_" method (has_pdf_preview). To have a better usability of preview_generator, we should know for all content if text, json, html, pdf, and jpeg preview should be available.

**Comment by lebouquetin** [comment]
@inkhey fixing this issue in a generic manner will probably be the subject of an engineer training for february 2019. For now, we must fix it for jpeg, so there are 2 issues: one to fix fast about `has_jpeg_preview()`, the other for fixing on a generic way

**Comment by lebouquetin** [comment]
@inkhey, the issue seems to be fixed (fix is merged), you confirm? If so, could you close the issue?

**Comment by inkhey** [comment]
yes.
