### ISSUE TITLE
Support encrpyted PDF preview

### ISSUE THREAD

**Issue by lebouquetin** [algoo/preview-generator#52]
Current status:
- when uploading an encrpyted PDF, even if there is no password protection, the preview will fail with the following error:

```
PyPDF2.utils.PdfReadError: file has not been decrypted
```

The issue is related to https://github.com/mstamy2/PyPDF2/issues/51

Expected:

Allow to preview encrypted PDF files if they are not password protected.

How to reproduce:

The attached PDF is encrpyted and fails.

How to fix it:

Replace

```
input_pdf = PdfFileReader(pdf, strict=False)
```

with the following code:

```
input_pdf = PdfFileReader(pdf, strict=False)
if input_pdf.isEncrypted:
    input_pdf.decrypt('')
```

**Comment by lebouquetin** [comment]
Encrpypted PDF: [edilkamin_mya_lou_ania_lea_dame_poele_etanche_cstb.pdf](https://github.com/algoo/preview-generator/files/2559082/edilkamin_mya_lou_ania_lea_dame_poele_etanche_cstb.pdf)

**Comment by lebouquetin** [comment]
MR for the fix: https://github.com/algoo/preview-generator/pull/53

**Comment by inkhey** [comment]
https://github.com/algoo/preview-generator/commit/48f5d62e61e597039dfff7d8cd50d353561aa025 fix issue for simple encryption (RC4 used by libreoffice for pdf v1.4).
We need a solution for more recent encrypted file, like example file here: https://github.com/tracim/tracim/issues/1126.

**Comment by anukuncheria** [comment]
NotImplementedError: only algorithm code 1 and 2 are supported

**Comment by inkhey** [comment]
@anukuncheria have you tried with qpdf ?
Support for other algorithms is obtained only if these dependencies are installed.
