### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by buchs** [algoo/preview-generator#64]
You might add a note on how to get the dependencies on Windows. For example, I just researched pdfinfo and it seems this application provides it: http://www.xpdfreader.com/download.html . I think you should also then note how the directory of that command _probably_ needs to be added to the PATH before Python is run.

**Comment by buxx** [comment]
Thank you for this. We will do that !

**Comment by inkhey** [comment]
I check a bit about what is needed for windows, as this platform is untested:

it should need at least :  
* **installed** exiftool for build : https://www.sno.phy.queensu.ca/~phil/exiftool/install.html, 
* imagemagick for running many builder: http://docs.wand-py.org/en/0.5.0/guide/install.html#install-imagemagick-on-windows
* and probably ghostscript for pdf: https://www.ghostscript.com/download/gsdnld.html
