### ISSUE TITLE
Version 0.8 or 0.9?

### ISSUE THREAD

**Issue by JulienPalard** [algoo/preview-generator#66]
The current devel branch announces v0.8 but on pypi I see v0.9, which one is wrong?

**Comment by buxx** [comment]
Hello,

Commit with version are done on master branch: https://github.com/algoo/preview-generator/blob/master/preview_generator/infos.py

Your remark is relevant: We will change our process.

**Comment by buxx** [comment]
I opened #67, thank's you for your issue.
