### ISSUE TITLE
PyPI description contains incorrect information (get_jpeg_preview and use_original_filename)

### ISSUE THREAD

**Issue by alexwlchan** [algoo/preview-generator#69]
I’ve installed preview-generator 0.9, and the PyPI description describes the following:

> **For images(GIF, BMP, PNG, JPEG, PDF) into jpeg :**
>
>     preview_manager = PreviewManager(cache_path)
>     preview = preview_manager.get_jpeg_preview(file_path,height=1024,width=526)
>
> -> Will create a preview from an image file into a jpeg file of size 1024 * 526
args :
>
>> file_path : the String of the path where is the file you want to get the preview
>> height : height of the preview in pixels
>> width : width of the preview in pixels. If not mentioned, width will be the same as height
>> use_original_filename : a boolean that mention if the original file name should appear in the preview name. True by default
>
> returns :
>
>> a FileIO stream of bytes of the jpeg preview

But if I try to use it, I get an error, because the actual code does something completely different.

https://github.com/algoo/preview-generator/blob/release_0.9/preview_generator/manager.py#L138-L157

```python
    def get_jpeg_preview(
            self,
            file_path: str,
            page: int = -1,
            width: int = None,
            height: int = 256,
            force: bool = False,
            file_ext: str = ''
    ) -> str:
        """
        Return a JPEG preview of given file, according to parameters
        :param file_path: path of the file to preview
        :param page: page of the original document, if it makes sense
        :param width: width of the requested preview image
        :param height: height of the requested preview image
        :param force: if True, do not use cached preview.
        :param file_ext: extension associated to the file. Eg 'jpg'. May be empty -
                it's usefull if the extension can't be found in file_path
        :return: path to the generated preview file
        """
```

This description (and probably that of similar methods) should be updated to reflect the current version of the library.

**Comment by buxx** [comment]
Hello @alexwlchan ,

You're right. Thank's for the issue we will fix that innext release !

**Comment by basilelegal** [comment]
Fixed, will be merge in next release
