### ISSUE TITLE
add qpdf to requirement in documentation

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#78]
Currently, we provided enhanced support of PDF decryption using qpdf but there is nothing about it in documentation

**Comment by antemooo** [comment]
In addition to the same thread, please add `sudo apt-get exiftool scribus` to the dependencies. People with Ubuntu minimal installation does not have these packages by default.

**Comment by lebouquetin** [comment]
@antemooo could you open another issue for these two dependencies?
