### ISSUE TITLE
strange preview result with xkcd images

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#84]
**Currently:**

Using tracim 2.2 RC1 using preview_generator preview-generator==0.10, i get some strange result in preview, with some xkcd images:

![xkcd_phone_6](https://user-images.githubusercontent.com/7851652/57465349-b767f500-727e-11e9-9af7-2f6be14783f2.png)
become:
![xkcd_phone_6](https://user-images.githubusercontent.com/7851652/57465328-af0fba00-727e-11e9-8767-ab215df25c1e.jpg)

another sample:
![test_copie](https://user-images.githubusercontent.com/7851652/57465500-0877e900-727f-11e9-87ec-4a6de1895e92.png)
become:
![test_copie](https://user-images.githubusercontent.com/7851652/57465541-1f1e4000-727f-11e9-8c0b-3d7461b93248.jpg)

**Expected:**

Better preview result for this kind of image.

**Comment by PhilippeAccorsi** [comment]
Same problem with older version of preview-generator (with png file).

**Comment by inkhey** [comment]
similar issue with https://upload.wikimedia.org/wikipedia/commons/8/8e/The_Wire_logo.png.

**Comment by PhilippeAccorsi** [comment]
Tested and its working good.
