### ISSUE TITLE
Mypy Travis continuous integration

### ISSUE THREAD

**Issue by herawo** [algoo/preview-generator#9]
http://mypy.readthedocs.io/en/latest/config_file.html
https://pypi.python.org/pypi/pytest-mypy

Check if there's a better way for checking mypy annotations in order to keep the .travis.yml the clearer possible.

**Comment by algooapy** [comment]
ie make the following command to work:
`py.test --mypy tests`

**Comment by herawo** [comment]
I already tried this, but the mypy command that i use in the travis.yml is :
`mypy preview_generator --ignore-missing-imports --disallow-untyped-defs`
and I did not find the equivalent of `--ignore-missing-imports --disallow-untyped-defs` with the `py.test --mypy tests`

**Comment by inkhey** [comment]
deprecated. we do have mypy in continous integration now
