### ISSUE TITLE
Tests broken on python 3.4 dues to Pillow 6

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#91]
## Bug description & symptom

Tests are broken with python 3.4 since travis try to install pillow 6.*

## Expected:

Need discussion:
2 solutions:
1. Drop support for python 3.4 in preview_generator, as:
   - python 3.4 is end of life.
    - python3.4 lack ssl 1.1 support (not easily able to use it in modern linux distrib).
   - pillow 6.* doesn't support it anymore(https://github.com/python-pillow/Pillow/pull/3596/files?short_path=548eb9c#diff-548eb9ce4cac8e13a1238ad703272931)
2. Make preview_generator need pilow 5.* version instead of last one.

**Comment by lebouquetin** [comment]
WONTFIX (we do not support python 3.4 anymore)
