### ISSUE TITLE
check_executable_is_available logging

### ISSUE THREAD

**Issue by JulienPalard** [algoo/preview-generator#98]
Due to an error in this logging line:

    logger.error("Error while checking dependencies: ", e)

I bet it has never logged (a `%s` is missing), it should have raised `TypeError: not all arguments converted during string formatting` instead.

I fixed it, here: https://github.com/algoo/preview-generator/pull/89/files#diff-4908662d10dd8b6ceab2890c6a908fdcR131

But I'm not a fan of having a line logged here, as it's a normal path, if the executable is not present, to cross this `except`. So I'd propose to just remove it.

What do you think? Why was it here in the first place?

- in f4beb13151180b09d4b48d9c44fe3238d2b7025f it was replaced from a print to a logger
- before that the print has always been here.

**Comment by buxx** [comment]
@inkhey Do you have a position about that ?
